FROM python:3.10

ENV FAASIT_PROVIDER=pku

# COPY ./serverless-framework /serverless-framework

# COPY ./faasit-runtime /faasit-runtime

# RUN pip install serverless_framework --index-url http://192.168.28.220:12121 --trusted-host 192.168.28.220


RUN pip install faasit-runtime --index-url http://192.168.28.220:12121 --trusted-host 192.168.28.220