POST http://0.0.0.0:9000 HTTP/1.1
Content-Type: application/json

{"text":"hello world"}

###
POST http://wordcount-executor.default.10.0.0.233.sslip.io/ HTTP/1.1
Content-Type: application/json

{"text":"hello world"}